// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: relationalai/lqp/v1/fragments.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *FragmentId            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Declarations  []*Declaration         `protobuf:"bytes,2,rep,name=declarations,proto3" json:"declarations,omitempty"`
	DebugInfo     *DebugInfo             `protobuf:"bytes,3,opt,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fragment) Reset() {
	*x = Fragment{}
	mi := &file_relationalai_lqp_v1_fragments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fragment) ProtoMessage() {}

func (x *Fragment) ProtoReflect() protoreflect.Message {
	mi := &file_relationalai_lqp_v1_fragments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fragment.ProtoReflect.Descriptor instead.
func (*Fragment) Descriptor() ([]byte, []int) {
	return file_relationalai_lqp_v1_fragments_proto_rawDescGZIP(), []int{0}
}

func (x *Fragment) GetId() *FragmentId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Fragment) GetDeclarations() []*Declaration {
	if x != nil {
		return x.Declarations
	}
	return nil
}

func (x *Fragment) GetDebugInfo() *DebugInfo {
	if x != nil {
		return x.DebugInfo
	}
	return nil
}

type DebugInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*RelationId          `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	OrigNames     []string               `protobuf:"bytes,2,rep,name=orig_names,json=origNames,proto3" json:"orig_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugInfo) Reset() {
	*x = DebugInfo{}
	mi := &file_relationalai_lqp_v1_fragments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugInfo) ProtoMessage() {}

func (x *DebugInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relationalai_lqp_v1_fragments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugInfo.ProtoReflect.Descriptor instead.
func (*DebugInfo) Descriptor() ([]byte, []int) {
	return file_relationalai_lqp_v1_fragments_proto_rawDescGZIP(), []int{1}
}

func (x *DebugInfo) GetIds() []*RelationId {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DebugInfo) GetOrigNames() []string {
	if x != nil {
		return x.OrigNames
	}
	return nil
}

type FragmentId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Variable-length identifier, up to 256 bits (32 bytes) or less
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FragmentId) Reset() {
	*x = FragmentId{}
	mi := &file_relationalai_lqp_v1_fragments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentId) ProtoMessage() {}

func (x *FragmentId) ProtoReflect() protoreflect.Message {
	mi := &file_relationalai_lqp_v1_fragments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentId.ProtoReflect.Descriptor instead.
func (*FragmentId) Descriptor() ([]byte, []int) {
	return file_relationalai_lqp_v1_fragments_proto_rawDescGZIP(), []int{2}
}

func (x *FragmentId) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_relationalai_lqp_v1_fragments_proto protoreflect.FileDescriptor

var file_relationalai_lqp_v1_fragments_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x61, 0x69, 0x2f, 0x6c,
	0x71, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x61, 0x69, 0x2e, 0x6c, 0x71, 0x70, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x61, 0x69, 0x2f, 0x6c, 0x71, 0x70, 0x2f, 0x76, 0x31, 0x2f,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x01, 0x0a, 0x08,
	0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x61, 0x69, 0x2e, 0x6c, 0x71, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x44, 0x0a, 0x0c, 0x64, 0x65, 0x63,
	0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x61, 0x69, 0x2e, 0x6c,
	0x71, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0c, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x3d, 0x0a, 0x0a, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x61, 0x69, 0x2e, 0x6c, 0x71, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x62, 0x75, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x64, 0x65, 0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5d,
	0x0a, 0x09, 0x44, 0x65, 0x62, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x61, 0x69, 0x2e, 0x6c, 0x71, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x69, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x1c, 0x0a,
	0x0a, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x42, 0x2c, 0x5a, 0x2a, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x2d, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x61, 0x69, 0x2f, 0x6c, 0x71, 0x70, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_relationalai_lqp_v1_fragments_proto_rawDescOnce sync.Once
	file_relationalai_lqp_v1_fragments_proto_rawDescData []byte
)

func file_relationalai_lqp_v1_fragments_proto_rawDescGZIP() []byte {
	file_relationalai_lqp_v1_fragments_proto_rawDescOnce.Do(func() {
		file_relationalai_lqp_v1_fragments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relationalai_lqp_v1_fragments_proto_rawDesc), len(file_relationalai_lqp_v1_fragments_proto_rawDesc)))
	})
	return file_relationalai_lqp_v1_fragments_proto_rawDescData
}

var file_relationalai_lqp_v1_fragments_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_relationalai_lqp_v1_fragments_proto_goTypes = []any{
	(*Fragment)(nil),    // 0: relationalai.lqp.v1.Fragment
	(*DebugInfo)(nil),   // 1: relationalai.lqp.v1.DebugInfo
	(*FragmentId)(nil),  // 2: relationalai.lqp.v1.FragmentId
	(*Declaration)(nil), // 3: relationalai.lqp.v1.Declaration
	(*RelationId)(nil),  // 4: relationalai.lqp.v1.RelationId
}
var file_relationalai_lqp_v1_fragments_proto_depIdxs = []int32{
	2, // 0: relationalai.lqp.v1.Fragment.id:type_name -> relationalai.lqp.v1.FragmentId
	3, // 1: relationalai.lqp.v1.Fragment.declarations:type_name -> relationalai.lqp.v1.Declaration
	1, // 2: relationalai.lqp.v1.Fragment.debug_info:type_name -> relationalai.lqp.v1.DebugInfo
	4, // 3: relationalai.lqp.v1.DebugInfo.ids:type_name -> relationalai.lqp.v1.RelationId
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_relationalai_lqp_v1_fragments_proto_init() }
func file_relationalai_lqp_v1_fragments_proto_init() {
	if File_relationalai_lqp_v1_fragments_proto != nil {
		return
	}
	file_relationalai_lqp_v1_logic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relationalai_lqp_v1_fragments_proto_rawDesc), len(file_relationalai_lqp_v1_fragments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relationalai_lqp_v1_fragments_proto_goTypes,
		DependencyIndexes: file_relationalai_lqp_v1_fragments_proto_depIdxs,
		MessageInfos:      file_relationalai_lqp_v1_fragments_proto_msgTypes,
	}.Build()
	File_relationalai_lqp_v1_fragments_proto = out.File
	file_relationalai_lqp_v1_fragments_proto_goTypes = nil
	file_relationalai_lqp_v1_fragments_proto_depIdxs = nil
}
