# Autogenerated using ProtoBuf.jl v1.2.0 on 2026-02-11T17:43:23.030
# original file: /Users/nystrom/rai/nn-meta-cleanup2/proto/relationalai/lqp/v1/fragments.proto (proto3 syntax)

import ProtoBuf as PB
using ProtoBuf: OneOf
using ProtoBuf.EnumX: @enumx

export FragmentId, DebugInfo, Fragment


struct FragmentId
    id::Vector{UInt8}
end
FragmentId(;id = UInt8[]) = FragmentId(id)
PB.default_values(::Type{FragmentId}) = (;id = UInt8[])
PB.field_numbers(::Type{FragmentId}) = (;id = 1)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:FragmentId})
    id = UInt8[]
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            id = PB.decode(d, Vector{UInt8})
        else
            Base.skip(d, wire_type)
        end
    end
    return FragmentId(id)
end

function PB.encode(e::PB.AbstractProtoEncoder, x::FragmentId)
    initpos = position(e.io)
    !isempty(x.id) && PB.encode(e, 1, x.id)
    return position(e.io) - initpos
end
function PB._encoded_size(x::FragmentId)
    encoded_size = 0
    !isempty(x.id) && (encoded_size += PB._encoded_size(x.id, 1))
    return encoded_size
end

struct DebugInfo
    ids::Vector{RelationId}
    orig_names::Vector{String}
end
DebugInfo(;ids = Vector{RelationId}(), orig_names = Vector{String}()) = DebugInfo(ids, orig_names)
PB.default_values(::Type{DebugInfo}) = (;ids = Vector{RelationId}(), orig_names = Vector{String}())
PB.field_numbers(::Type{DebugInfo}) = (;ids = 1, orig_names = 2)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:DebugInfo})
    ids = PB.BufferedVector{RelationId}()
    orig_names = PB.BufferedVector{String}()
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, ids)
        elseif field_number == 2
            PB.decode!(d, orig_names)
        else
            Base.skip(d, wire_type)
        end
    end
    return DebugInfo(ids[], orig_names[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::DebugInfo)
    initpos = position(e.io)
    !isempty(x.ids) && PB.encode(e, 1, x.ids)
    !isempty(x.orig_names) && PB.encode(e, 2, x.orig_names)
    return position(e.io) - initpos
end
function PB._encoded_size(x::DebugInfo)
    encoded_size = 0
    !isempty(x.ids) && (encoded_size += PB._encoded_size(x.ids, 1))
    !isempty(x.orig_names) && (encoded_size += PB._encoded_size(x.orig_names, 2))
    return encoded_size
end

struct Fragment
    id::Union{Nothing,FragmentId}
    declarations::Vector{Declaration}
    debug_info::Union{Nothing,DebugInfo}
end
Fragment(;id = nothing, declarations = Vector{Declaration}(), debug_info = nothing) = Fragment(id, declarations, debug_info)
PB.default_values(::Type{Fragment}) = (;id = nothing, declarations = Vector{Declaration}(), debug_info = nothing)
PB.field_numbers(::Type{Fragment}) = (;id = 1, declarations = 2, debug_info = 3)

function PB.decode(d::PB.AbstractProtoDecoder, ::Type{<:Fragment})
    id = Ref{Union{Nothing,FragmentId}}(nothing)
    declarations = PB.BufferedVector{Declaration}()
    debug_info = Ref{Union{Nothing,DebugInfo}}(nothing)
    while !PB.message_done(d)
        field_number, wire_type = PB.decode_tag(d)
        if field_number == 1
            PB.decode!(d, id)
        elseif field_number == 2
            PB.decode!(d, declarations)
        elseif field_number == 3
            PB.decode!(d, debug_info)
        else
            Base.skip(d, wire_type)
        end
    end
    return Fragment(id[], declarations[], debug_info[])
end

function PB.encode(e::PB.AbstractProtoEncoder, x::Fragment)
    initpos = position(e.io)
    !isnothing(x.id) && PB.encode(e, 1, x.id)
    !isempty(x.declarations) && PB.encode(e, 2, x.declarations)
    !isnothing(x.debug_info) && PB.encode(e, 3, x.debug_info)
    return position(e.io) - initpos
end
function PB._encoded_size(x::Fragment)
    encoded_size = 0
    !isnothing(x.id) && (encoded_size += PB._encoded_size(x.id, 1))
    !isempty(x.declarations) && (encoded_size += PB._encoded_size(x.declarations, 2))
    !isnothing(x.debug_info) && (encoded_size += PB._encoded_size(x.debug_info, 3))
    return encoded_size
end
